retrieve_task: 
    description: >
       Retrieve policy documents for user query : {query}

    agent: retriever_agent

    expected_output: >
       A list of the most relevant policy document excerpts.


analysis_task: 
    description: >
      Analyze retrieved policies

    agent: policy_agent

    context: [retrieve_task]

    expected_output: >
       A clear analysis and interpretation of the retrieved policy text


final_task: 
    description: >
       Generate final answer with references

    agent: answer_agent

    context: [analysis_task]

    expected_output: >
       A concise and accurate answer citing relevant company policy sections.


